version: '3.8'

services:
  eureka-server:
    build: ./Eureka
    ports:
      - "8761:8761"
    networks:
      - booki-network

  book-service:
    build: ./GestionLivres
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8095:8095"
    networks:
      - booki-network
    depends_on:
      - eureka-server

  cart-service:
    build: ./Cart
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - booki-network
    depends_on:
      - eureka-server
      - book-service

networks:
  booki-network:
    driver: bridge